### ISSUE TITLE
Aggiungere formato SVG

### ISSUE THREAD

**Issue by jenkin** [ondata/confini-amministrativi-istat#15]
Sarebbe interessante offrire anche un rendering vettoriale dello shapefile in formato SVG con l'aspect ratio del bounding box della geometria. In questo modo si potrebbe embeddare facilmente in una pagina web come immagine.

```[tasklist]
### Tasks
- [x] Trovare una libreria che effettui la conversione shapefile --> svg
- [x] Testare la soluzione su shapefile reali
- [x] Integrarla nello script di generazione
- [x] Aggiornare la documentazione openapi
```

**Comment by jenkin** [comment]
Pre-requisiti: [python](https://www.python.org/).

**Comment by jenkin** [comment]
Ho testato [svgis](https://svgis.readthedocs.io/en/stable/index.html) e funziona benone, aprirò una PR nei prossimi giorni.

![image](https://github.com/ondata/confini-amministrativi-istat/assets/426495/7e0cc5cb-0678-4fe8-9c87-b8997023de3f)
