### ISSUE TITLE
Aggiungere formati immagine raster (PNG, JPG, WEBP)

### ISSUE THREAD

**Issue by jenkin** [ondata/confini-amministrativi-istat#16]
Implementata la #15 sarebbe interessante generare anche immagini raster degli shapefile, in questo caso in due varianti (nero su sfondo bianco / trasparente e bianco su sfondo nero / trasparente) e a varie risoluzioni verticali.

```[tasklist]
### Tasks
- [x] Trovare una libreria che effettui la conversione svg --> png, jpg, webp
- [x] Testare la soluzione su shapefile reali
- [x] Integrarla nello script di generazione
- [x] Aggiornare la documentazione openapi
```

**Comment by jenkin** [comment]
Pre-requisiti: [python](https://www.python.org/).
