### ISSUE TITLE
Mappa - facendo pan la retinatura del comune scopre una fascia a sud della mappa

### ISSUE THREAD

**Issue by lorenzoperone** [ondata/confini-amministrativi-istat#5]
La fascia scoperta non sembra più appartenere al comune.
Complimenti Alessio è sempre bello vedere le cose belle che fai :)
![Schermata 2024-02-02 alle 19 44 23](https://github.com/ondata/confini-amministrativi-istat/assets/5204799/d9e8b7e3-e262-4bbe-bd50-d66fa552dcee)

```[tasklist]
### Tasks
- [ ] Riprodurre il bug
- [ ] Cercare risorse per una soluzione
- [ ] Implementare una soluzione
- [ ] Aprire una PR
```

**Comment by jenkin** [comment]
Questa è una buona _first issue_!

Pre-requisiti: [js](https://developer.mozilla.org/en-US/docs/Web/JavaScript), [parcel](https://parceljs.org/), [leaflet](https://leafletjs.com/).
